[[section-architecture-constraints]]
== Randbedingungen

[role="arc42help"]
****
.Inhalt
Randbedingungen und Vorgaben, die ihre Freiheiten bezüglich Entwurf, Implementierung oder Ihres Entwicklungsprozesses einschränken.
Diese Randbedingungen gelten manchmal organisations- oder firmenweit über die Grenzen einzelner Systeme hinweg.

.Motivation
Für eine tragfähige Architektur sollten Sie genau wissen, wo Ihre Freiheitsgrade bezüglich der Entwurfsentscheidungen liegen und wo Sie Randbedingungen beachten müssen.
Sie können Randbedingungen vielleicht noch verhandeln, zunächst sind sie aber da.

.Form
Einfache Tabellen der Randbedingungen mit Erläuterungen.
Bei Bedarf unterscheiden Sie technische, organisatorische und politische Randbedingungen oder übergreifende Konventionen (beispielsweise Programmier- oder Versionierungsrichtlinien, Dokumentations- oder Namenskonvention).


.Weiterführende Informationen

Siehe https://docs.arc42.org/section-2/[Randbedingungen] in der online-Dokumentation (auf Englisch!).

****

=== Technische Randbedingungen

[cols="3,3" options="header"]
|===
|Randbedingung |Erläuterung
| Hardware | Das System soll auf einem Raspberry Pi 4 laufen.
| Implementierung in Java |Im Rahmen der Projektschiene wird Java verwendet.
|===

=== Organisatorische Randbedingungen

[cols="3,5" options="header"]
|===
|Randbedingung |Erläuterung
| Team | Unser Projektteam, unterstützt durch Teamcoach.
| Budget | Das Budget für das Projekt beträgt 200 CHF.
| Zeitplan | Beginn des Projektes August 2023, Ende im August 2024, Zeitbudget: 180 Stunden pro Person pro Semester.
| Vorgehensmodell | Im Projekt wird mit dem RUP Modell gearbeitet.
| Versionsverwaltung | Versionsverwaltung mit Git auf Gitlab.
|===
